workflows:
  build_macos:
    name: Build Electron App for macOS
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - npm install
      - npm run dist
    artifacts:
      - dist/**/*.dmg
      - dist/**/*.zip
      - dist/**/*.app
    cache:
      cache_paths:
        - $HOME/.npm
