workflows:
  build_macos:
    name: Build Electron App for macOS
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - rm -rf node_modules package-lock.json
      - npm install
      - npm run dist:mac
    artifacts:
      - dist/*.dmg
      - dist/*.zip
      - dist/mac/*.app
    cache:
      cache_paths:
        - $HOME/.npm